### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by kazu82018303** [GeorgeSeif/Semantic-Segmentation-Suite#102]
1. Feature requests
------------------------
1．I am augumentation in C ++,
Since there are various augmentation types readily available on this code, are there plans to increase it in the future?

2．Are you planning to enable video to be input to test?

**Comment by GeorgeSeif** [comment]
(1) Maybe if I find one that is useful :) But for now the ones in the repo are more than enough for most people

(2) Nope!
