### ISSUE TITLE
mobilenetv2+deeplabv3 is not working well

### ISSUE THREAD

**Issue by 1453042287** [GeorgeSeif/Semantic-Segmentation-Suite#106]
- **What are your command line arguments?:**
      --model="DeepLabV3"  --frontend="MobileNetV2"
- **Have you written any custom code?**:
      no
- **What have you done to try and solve this issue?:**
      nothing
- **TensorFlow version?**:
      tf-gpu 1.41

### Describe the problem

 i use the mobilenetv2+deeplabv3 to train the Camvid use the default setting, but the resault is vary bad, like this:
![0006r0_f02550_pred](https://user-images.githubusercontent.com/41471119/45962120-b61ceb80-c052-11e8-937c-71c298624e2e.png)
is there something wrong? can you give me some suggestions? thanks a lot!

### Source code / logs

[2018-09-22 11:21:43] Epoch = 0 Count = 20 Current_Loss = 3.5813 Time = 15.45
[2018-09-22 12:21:29] Epoch = 11 Count = 20 Current_Loss = 0.6431 Time = 14.80
the loss is very low but the iou is also very low:
Average validation accuracy for epoch # 0011 = 0.744530
Validation precision =  0.8331654035569068
Validation recall =  0.7445304870605469
Validation F1 score =  0.7709636802899439
Validation IoU score =  0.23818708291145957
and same with the 300th epoch:
[2018-09-23 17:20:44] Epoch = 299 Count = 20 Current_Loss = 0.2304 Time = 15.28
Average validation accuracy for epoch # 0299 = 0.825447
Validation precision =  0.8542661199801472
Validation recall =  0.8254470825195312
Validation F1 score =  0.8317509957405742
Validation IoU score =  0.3643499687354822

**Comment by GeorgeSeif** [comment]
Was the default image size you used 512x512? 

There are really 2 possible cases here:

(1) The model is not good enough for high IoU

(2) The image size is too small for high IoU since the original image size is quite large

Try playing around with those 2 and see what happens :)

**Comment by 111Moderato** [comment]
@GeorgeSeif 
I also use DeepLabV3+MobileNetV2.
But the pre training model of MobileNetV2 that I download after I start the command will cause this error:
`tensorflow.python.framework.errors_impl.DataLossError: Unable to read file (models/mobilenet_v2.ckpt.index). Perhaps the file is corrupt or was produced by a newer version of TensorFlow with format changes (failed to seek to header entry): corrupted compressed block contents`

**Comment by GeorgeSeif** [comment]
This is not a critical error and can be safely ignored. Try the suggestions I gave above :)

Closing due to lack of information.
