### ISSUE TITLE
Difference between frontend and model

### ISSUE THREAD

**Issue by under94** [GeorgeSeif/Semantic-Segmentation-Suite#113]
Hi,
I'm new in tensorflow. I don't understand the difference about frontend and model.
Are the models an extention of frontends? I saw that for some models the weights of the resnet are loaded.
Then, is there a way to use as model only InceptionV4 or a Resnet (so, a frontend)?

Thanks.

**Comment by GeorgeSeif** [comment]
Frontends are for feature extraction of the segmentation models. Try reading some of the linked papers!
