### ISSUE TITLE
Predict.py   Line54

### ISSUE THREAD

**Issue by Darknesszlx** [GeorgeSeif/Semantic-Segmentation-Suite#114]
resized_image =cv2.resize(loaded_image, (args.crop_width, args.crop_width))
it should be resized_image =cv2.resize(loaded_image, (args.crop_width, args.crop_height))?

**Comment by GeorgeSeif** [comment]
You're right! Just fixed it :)

**Comment by cena001plus** [comment]
> resized_image =cv2.resize(loaded_image, (args.crop_width, args.crop_width))
> it should be resized_image =cv2.resize(loaded_image, (args.crop_width, args.crop_height))?

what's the  different??  i have no idea.  @Darknesszlx
