### ISSUE TITLE
Small bug report: iterator should return strings, not bytes

### ISSUE THREAD

**Issue by HIN0209** [GeorgeSeif/Semantic-Segmentation-Suite#12]
@GeorgeSeif 
I enjoy your code. python main.py threw a following error: 
File "./helpers.py", line 26, in get_class_dict
    header = next(file_reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

It seems like a small typo.
https://stackoverflow.com/questions/8515053/csv-error-iterator-should-return-strings-not-bytes
I changed the line 24 of helpers.py and it worked, so just FYI.
FROM with open(csv_path, 'rb') as csvfile:
TO: with open(csv_path, 'r') as csvfile:

**Comment by GeorgeSeif** [comment]
Ah I see. Thanks for that! I'll update that function in the next push!
