### ISSUE TITLE
Problem with dataset  (51x71x1)

### ISSUE THREAD

**Issue by diegoaichele** [GeorgeSeif/Semantic-Segmentation-Suite#121]
i have the next problem.
`Traceback (most recent call last):
  File "train.py", line 176, in <module>
    output_image = utils.load_image(train_output_names[id])
  File "/home/seth/Desktop/Semantic-Segmentation-Suite/utils/utils.py", line 45, in load_image
    image = cv2.cvtColor(cv2.imread(path,-1), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/color.hpp:255: error: (-2:Unspecified error) i                            n function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray,                             int) [with VScn = cv::Set<3, 4>; VDcn = cv::Set<3, 4>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizeP                            olicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_Outp                            utArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1
`

I generate on matlab matrix to image with imwrite(matrix, name.png) this generate a image of 51x71x1 (so i had a gray image (on input image and outputimage) )

i generate the next class dictonary:
name,r,g,b
Background,0,0,0
Object,255,255,255

`

**Comment by diegoaichele** [comment]
LOL, i change the image to 51x71x3

**Comment by GeorgeSeif** [comment]
Well as mentioned in the FAQ, 51x71 will be far too small due to the downsampling. You could always try upscaling your images beforehand though!
