### ISSUE TITLE
Using grayscale images

### ISSUE THREAD

**Issue by abderhasan** [GeorgeSeif/Semantic-Segmentation-Suite#126]
Hello,

Thanks so much for your nice work. I'm using grayscale images and get the following when trying to train the model:

```
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    output_image = np.float32(helpers.one_hot_it(label=output_image, label_values=label_values))
  File "/home/me/Desktop/Semantic-Segmentation-Suite/utils/helpers.py", line 68, in one_hot_it
    equality = np.equal(label, colour)
ValueError: operands could not be broadcast together with shapes (512,512) (3,) 
```
I saw kind of a similar question in the issues, but was related to the label. So, should I convert the images and their labels to color (RGB) images?

Thanks.

**Comment by GeorgeSeif** [comment]
Yes convert to RGB. You could modify the code to do grey scale, but writing a quick script to go from grey scale to RGB will be much easier and faster :)
