### ISSUE TITLE
error: get_pretrained_checkpoints.py

### ISSUE THREAD

**Issue by HIN0209** [GeorgeSeif/Semantic-Segmentation-Suite#13]
@GeorgeSeif 
get_pretrained_checkpoints.py returned the following error. Worked fine for vgg and inception_v2-v4.
(python 3.5.4).

Any suggestion? Thank you!! 

-----------------------------
mv: cannot stat 'inception_resnet_v2.ckpt'. No such file or directory.
Traceback (most recent call last):
  File "get_pretrained_checkpoints.py", line 41, in <module>
    subprocess.check_output(['mv', 'inception_resnet_v2.ckpt', 'weights'])
  File "/home/me/anaconda3/envs/tensorflow/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/home/me/anaconda3/envs/tensorflow/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mv', 'inception_resnet_v2.ckpt', 'weights']' returned non-zero exit status 1

**Comment by GeorgeSeif** [comment]
Hi there,

The "get_pretrained_checkpoints.py" does 2 things for each pretrained network:

1. Download the weights

2. Move the weights into a new folder

As your error says "No such file or directory." it means that it can't find the file named "inception_resnet_v2.ckpt". So one of two things happened. Either the file was not downloaded correctly (check the folder where you run the script) or the weights file you downloaded for the Inception ResNetV2 network does not have the name "inception_resnet_v2.ckpt" (the authors who posted that weight file could have changed the name at any time). In the second case you can just rename the file and move it. So check that out.

**Comment by HIN0209** [comment]
Thank you for the response.
Yes, it was downloaded and located in the root directory.
But the problem appears that moving the ckpt file to weights (located in the root directory) caused an error with "python main.py --model RefineNet-Res50" because "Failed to find any matching files for models/resnet_v2_50.ckpt". I just moved the extracted resnet_v2_50.ckpt to the model folder (without moving to weights) and the training worked well.

Does it make sense?

**Comment by GeorgeSeif** [comment]
Yup that sounds correct!
