### ISSUE TITLE
Suggestion: ICNet and AdapNet

### ISSUE THREAD

**Issue by Tamme** [GeorgeSeif/Semantic-Segmentation-Suite#14]
Hi.

These two segmentation networks have recetly been very interesting.

The first already has a implementation https://github.com/hellochick/ICNet-tensorflow, but maybe you also want to add it here and the second one http://deepscene.cs.uni-freiburg.de/ has really cool fusion techniques although the model inside it is just resnet50.

So if you find these interesting and want to experiment with these then I would be very happy :)

I might even try adding icnet myself.

**Comment by GeorgeSeif** [comment]
Hey Tamme,

Good suggestions and will do. My GPU has been in use for a while now for research, but I'll get to those as soon as I can!

**Comment by GeorgeSeif** [comment]
I just added AdapNet!

It's slightly modified as I use bilinear upscaling rather than transposed convolutions since I found it gave better results and was easier to train.

**Comment by Tamme** [comment]
Cool! I will check it out when I find the time!
