### ISSUE TITLE
How do I use input data with shape (width, height, 1)?

### ISSUE THREAD

**Issue by hjp1101** [GeorgeSeif/Semantic-Segmentation-Suite#16]
Thanks for your code! Your code is working well on the RGB dataset.

I'm trying to use my own gray image dataset.
I changed code of input placeholoder and imread  as below, however I had a error.
**[change code of main.py]**
 `input = tf.placeholder(tf.float32, shape=[None, None, None, 1])`
 `input_image = cv2.imread(train_input_names[id], cv2.IMREAd_GRAYSCALE)`
**[change code of utils.py]**
line 60 `return image[y:y + crop_height, x:x + crop_width], label[y:y + crop_height, x:x + crop_width]`
**[error msg.]**
`File "main.py", line 277, in <module>`
 `_, current = sess.run([opt, loss], feed_dict={input: input_image_batch, output: output_image_batch})`
 `ValueError : Cannot feed value of shape (1, 640, 512) for Tensor 'Placeholder:0', which has shap '(?, ?, ?, 1)'`

How do I use input data with shape (width, height, 1) like gray image?

**Comment by hjp1101** [comment]
I solved the issue. 
`input_image = np.reshape(input_image, (input_image.shape[0], input_image.shape[1], 1))`

**Comment by GeorgeSeif** [comment]
Good to hear!
