### ISSUE TITLE
Error importing the image - !_src.empty()

### ISSUE THREAD

**Issue by freddifederica** [GeorgeSeif/Semantic-Segmentation-Suite#176]
### Information
- **What are your command line arguments?:**
python3 train.py --num_epochs 10 --checkpoint_step 1 --validation_step 1 --dataset Dyson --batch_size 2 --num_val_images 3 --h_flip 1 --v_flip 0 --brightness 0.6 --rotation 10 --model PSPNet --frontend ResNet152
- **Have you written any custom code?**:
No
- **What have you done to try and solve this issue?:**
I tried to executer the command multiple times but this error comes up every time, sometimes at the start or sometimes already after the count is already 20 or 40 (like in the image attached). 
- **TensorFlow version?**:
1.12.0-dev20181009

### Describe the problem
I am stuck with this problem every time I try to execute the train command described above as above:
```
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    input_image = utils.load_image(train_input_names[id])
  File "/code/Semantic-Segmentation-Suite-master/utils/utils.py", line 45, in load_image
    image = cv2.cvtColor(cv2.imread(path,-1), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```
To give you a better idea of how it look and when it happens:

<img width="1007" alt="screenshot 2019-01-13 at 14 38 33" src="https://user-images.githubusercontent.com/37051452/51086789-be548000-1742-11e9-8496-99bd09f02033.png">

I also tried to look if there might have been an issue with the name of the files and if I might have something missing in the train and train_labels folder but it does not look so to me, this is the content of the two folders:

<img width="919" alt="screenshot 2019-01-13 at 14 48 58" src="https://user-images.githubusercontent.com/37051452/51086764-97964980-1742-11e9-9997-d5980163a3fb.png">

I am not really sure what is going on, could anyone help? Thanks a lot.

**Comment by kemangjaka** [comment]
Did you try to print the path of input images and figure out which image is causing the error?

**Comment by freddifederica** [comment]
Solves, it was trying to open 
/code/Semantic-Segmentation-Suite-master/Dyson/train/.DS_Store
Thanks
