### ISSUE TITLE
Removing OpenCV Dependency?

### ISSUE THREAD

**Issue by fzyzcjy** [GeorgeSeif/Semantic-Segmentation-Suite#188]
### Information

- **What are your command line arguments?:** N/A
- **Have you written any custom code?**: N/A
- **What have you done to try and solve this issue?:** Do you need me to make a PR?
- **TensorFlow version?**: N/A

### Describe the problem
Feature request: Shall we remove the opencv dependency? I have checked the src code, finding that it is simply used to do some image reading/writing. Since opencv is a little bit more difficult to install than similar packages like scikit image tools, shall we remove the opencv dependency? Or, shall we allow the user to choose dependency of either opencv or scikit image?
Thank you very much for your wonderful library!

### Source code / logs
N/A

**Comment by lyyiangang** [comment]
install opencv via command pip3 install opencv-python

**Comment by fzyzcjy** [comment]
yes I found it later and thus closed this issue
