### ISSUE TITLE
Multi-Gpu Training

### ISSUE THREAD

**Issue by deeptf** [GeorgeSeif/Semantic-Segmentation-Suite#19]
Hi @GeorgeSeif : Do we have a direct way to enable multi-gpu training in a single machine for this codebase ?

**Comment by GeorgeSeif** [comment]
Hhmmm I'm not sure, never tried it, but that's definitely a good suggestion!

I'll look into it.

**Comment by vikjet** [comment]
Hi @GeorgeSeif : Did you ever get a chance to implement multi-gpu training support for any of the models?
