### ISSUE TITLE
Pretrained weights not available

### ISSUE THREAD

**Issue by jesarte** [GeorgeSeif/Semantic-Segmentation-Suite#201]
### Describe the problem
Some of the pretrained weights for the frontends are not available. I have tried all frontends: ResNet50, ResNet152, MobileNetV2 and InceptionV4, and all fail at the same point. 

### Source code / logs
Preparing the model ...
--2019-03-22 09:44:10--  https://s3.amazonaws.com/pretrained-weights/mobilenet_v2.ckpt.meta
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.114.44
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.114.44|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-03-22 09:44:11 ERROR 404: Not Found.

Traceback (most recent call last):
  File "utils/get_pretrained_checkpoints.py", line 21, in <module>
    subprocess.check_output(['wget','https://s3.amazonaws.com/pretrained-weights/mobilenet_v2.ckpt.meta', "-P", "models"])
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['wget', 'https://s3.amazonaws.com/pretrained-weights/mobilenet_v2.ckpt.meta', '-P', 'models']' returned non-zero exit status 8.
Traceback (most recent call last):
  File "./train.py", line 100, in <module>
    network, init_fn = model_builder.build_model(model_name=args.model, frontend=args.frontend, net_input=net_input, num_classes=num_classes, crop_width=args.crop_width, crop_height=args.crop_height, is_training=True)
  File "/content/gdrive/My Drive/Sync/Semantic-Segmentation-Suite/builders/model_builder.py", line 51, in build_model
    download_checkpoints("MobileNetV2")
  File "/content/gdrive/My Drive/Sync/Semantic-Segmentation-Suite/builders/model_builder.py", line 28, in download_checkpoints
    subprocess.check_output(["python", "utils/get_pretrained_checkpoints.py", "--model=" + model_name])
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', 'utils/get_pretrained_checkpoints.py', '--model=MobileNetV2']' returned non-zero exit status 1.

**Comment by iambackit** [comment]
> ### Describe the problem
> Some of the pretrained weights for the frontends are not available. I have tried all frontends: ResNet50, ResNet152, MobileNetV2 and InceptionV4, and all fail at the same point.
> 
> ### Source code / logs
> Preparing the model ...
> --2019-03-22 09:44:10-- https://s3.amazonaws.com/pretrained-weights/mobilenet_v2.ckpt.meta
> Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.114.44
> Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.114.44|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2019-03-22 09:44:11 ERROR 404: Not Found.
> 
> Traceback (most recent call last):
> File "utils/get_pretrained_checkpoints.py", line 21, in 
> subprocess.check_output(['wget','https://s3.amazonaws.com/pretrained-weights/mobilenet_v2.ckpt.meta', "-P", "models"])
> File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
> **kwargs).stdout
> File "/usr/lib/python3.6/subprocess.py", line 418, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['wget', 'https://s3.amazonaws.com/pretrained-weights/mobilenet_v2.ckpt.meta', '-P', 'models']' returned non-zero exit status 8.
> Traceback (most recent call last):
> File "./train.py", line 100, in 
> network, init_fn = model_builder.build_model(model_name=args.model, frontend=args.frontend, net_input=net_input, num_classes=num_classes, crop_width=args.crop_width, crop_height=args.crop_height, is_training=True)
> File "/content/gdrive/My Drive/Sync/Semantic-Segmentation-Suite/builders/model_builder.py", line 51, in build_model
> download_checkpoints("MobileNetV2")
> File "/content/gdrive/My Drive/Sync/Semantic-Segmentation-Suite/builders/model_builder.py", line 28, in download_checkpoints
> subprocess.check_output(["python", "utils/get_pretrained_checkpoints.py", "--model=" + model_name])
> File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
> **kwargs).stdout
> File "/usr/lib/python3.6/subprocess.py", line 418, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['python', 'utils/get_pretrained_checkpoints.py', '--model=MobileNetV2']' returned non-zero exit status 1.

I have the same issue.

**Comment by jsolves** [comment]
The Commit on Mar 7, 2019 has updated urls (that may work)...

**Comment by jesarte** [comment]
Those seem to work! Thank you very much!

**Comment by yucheng-china** [comment]
I have tried to use the new url, but this issue still happend, could you mind tell me how to slove it ?

**Comment by iambackit** [comment]
> I have tried to use the new url, but this issue still happend, could you mind tell me how to slove it ?

Sadly I couldn't solve that problem, so I found another project.
