### ISSUE TITLE
gt pictures in checkpoints different with val_labels?

### ISSUE THREAD

**Issue by x7hkvip** [GeorgeSeif/Semantic-Segmentation-Suite#202]
**what I have done:**
Papered my own dataset.
I wrote a script to convert 8 bit gray label pictures into 24 bit RGB pictures.
Then I modified csv files.
**what's the problems?**
When training,I found the ground truth pictures in checkpoints files are different to the lables in val_labels files(quite different!).
The predit pictures I got are all totally black pictures,but the current_loss isn't equals to 0.
**What should I do?Very appricate for your help!**

**Comment by x7hkvip** [comment]
I fixed it.The reason why I got this problem because when after I set color to my 8 bit gray picture,I convert it from png to jpg,this step add a lot of strange RGB values into my pictures.

**Comment by zihao0821** [comment]
> I fixed it.The reason why I got this problem because when after I set color to my 8 bit gray picture,I convert it from png to jpg,this step add a lot of strange RGB values into my pictures.

Hello, 

I use opencv to covert a *.png to *.jpg, and face the same problem. Can you tell to deal with that?

thanks！

**Comment by zihao0821** [comment]
> I fixed it.The reason why I got this problem because when after I set color to my 8 bit gray picture,I convert it from png to jpg,this step add a lot of strange RGB values into my pictures.

Oh, I find a way. Just convert a 8 bit .png to 24 bit .png :)
