### ISSUE TITLE
Refinenet model's problem

### ISSUE THREAD

**Issue by xxktju** [GeorgeSeif/Semantic-Segmentation-Suite#21]
Hi George,
In the MultiResolutionFusion function of Refinenet,should we upsample the rcu_low rather than the rcu_high according to the paper?

**Comment by xxktju** [comment]
And in the ChainedResidualPooling function of Refinenet, I think the second pooling block's input should be the 'net' rather than the 'net_relu', because 'net' is the first pooling block's output according to the paper

**Comment by xxktju** [comment]
In the MultiResolutionFusion function of Refinenet, why the low_inputs and high_inputs each has two dimensions 'low_inputs[0]','low_inputs[1]',the paper only has one dimension

**Comment by xxktju** [comment]
I think the most problem is in the RefineBlock. In the RefineBlock of this model, there are two RCU connected sequentially rather than parallel according to the paper, but the code of this model process the refinenet's input image by parallelly,so the low_inputs and high_inputs each has two dimensions ,maybe is wrong

**Comment by GeorgeSeif** [comment]
Hi @xxktju 
Awesome picking those up! Funny enough it trained just fine before and got good performance... But yes your correction are right!

I've just fixed the code and pushed it after reviewing your comments and the paper.

Cheers!
