### ISSUE TITLE
Class balancing

### ISSUE THREAD

**Issue by Tamme** [GeorgeSeif/Semantic-Segmentation-Suite#22]
Hi.

It seems that the networks basically ignore minority classes (eg road signs, lamp posts etc). Have you considered adding some balancing schemes also or you haven't found such an issue?

**Comment by GeorgeSeif** [comment]
I actually have a function for Median Frequency Balancing inside the `utils.py`. I haven't tested it much though, will probably have a few optional methods for class balancing soon, I'll put it in the "coming soon" section of the README. 

I found that early on in training yes the network mostly ignores the underrepresented classes, but later on it performs decently well on those classes, though probably not as well as if we weighted the classes. 

Anyways, I'll add that functionality in once I have a chance, but for now you can get some pretty good results.

Cheers!

**Comment by GeorgeSeif** [comment]
Also keeping this issue open as a reminder until I add it in!

**Comment by GeorgeSeif** [comment]
I just added my own implementation of class balancing that simply computes the weights according to the number of pixels for each class in the dataset. Check it out in the latest commit!

I'll try and look at the median frequency balancing and other methods in the future too to have more options.

Cheers!
