### ISSUE TITLE
PSPNet's model's Probelm

### ISSUE THREAD

**Issue by xxktju** [GeorgeSeif/Semantic-Segmentation-Suite#26]
Hi, George! I'm coming again!
In the PSPNet, the paper uses a pretrained ResNet model with the dilated network strategy, because using the dilated convolution, the final feature map size is 1/8 of the input image,but in the code of your PSPNet ,you directly use "end_points['pool3']" as the input of PyramidPoolingModule, although the feature map's size is 1/8, the receptive field decreases,so the rusult is not much better .Using the dilated convolution to gain 1/8 feature map is better!

**Comment by GeorgeSeif** [comment]
Hi again!

Yes you are right. The only reason I used that ResNet without dilation is because it has pre-trained weights. I couldn't find a pre-trained dilation model. If you know of any that I can use then I'd love to try it though!

**Comment by littlebelly** [comment]
@GeorgeSeif 
Maybe you can use the ResNet's parameters to initialize the pspnet model to train (just copy the same parameters of normal convolution kernel of normal Resnet to the dilated one of pspnet), it will be better.
