### ISSUE TITLE
RESNET checkpoints - no mention in doc

### ISSUE THREAD

**Issue by roestigraben** [GeorgeSeif/Semantic-Segmentation-Suite#29]
Hello,

maybe not a big thing as one can debug the problem rather easily. But can you update the documention that mentions that RESNET needs checkpoints and better run the script to get it. Or even better to incorporate the script into the main.py file

Thanks
Peter

**Comment by GeorgeSeif** [comment]
It is in the doc under the Models section and I just added it to the Usage section.

But good idea to call that script from `main.py`. I'll add that in!

**Comment by roestigraben** [comment]
Thanks a lot

I saw that the info I missed was nicely in the README file. I should have read it more carefully

cheers
Peter

**Comment by GeorgeSeif** [comment]
I just added a functionality to auto download the ResNet checkpoints anyways!

Cheers!
