### ISSUE TITLE
Should we including the unlabeled class?

### ISSUE THREAD

**Issue by lixiang-ucas** [GeorgeSeif/Semantic-Segmentation-Suite#3]
In your release code, you considered the unlabeled class and set the number of output to 12, rather than 11 (used by the paper author). And you got a global accuracy less than paper author, but the class average accuracy is higher than it. This confused me. Should I consider the unlabeled class when conducting my experiments? Specifically, i'm using the FC-DenseNet to conduct building extraction. Which means i only want to classify out the building class. Which way should i choose?Thanks for you patience.

**Comment by GeorgeSeif** [comment]
Hello again :)

You should definitely include the unlabeled classes (i.e use 12 with CamVid). Reason being is that if you were to go through the label images in CamVid, you'll find that some of them do in fact have 12 classes, with one of course being the "unlabeled" category. You can check that by doing something like this: Loop through the images, read them in, and check how many unique labels each one has. 

Specifically, the following **test images** have 12 unique labels:  '0001TP_009540.png',  '0001TP_009570.png',  '0001TP_009600.png',  '0001TP_009930.png',  '0001TP_009960.png', 'Seq05VD_f00240.png', 'Seq05VD_f00630.png', 'Seq05VD_f00720.png', 'Seq05VD_f00750.png',  'Seq05VD_f00780.png', 'Seq05VD_f00810.png',  'Seq05VD_f00840.png',  'Seq05VD_f03240.png',  'Seq05VD_f03960.png',  'Seq05VD_f04860.png'.

Now in terms of the accuracy. Keep in mind I did no data augmentation, no fine tuning, and did not use any class weights at all; those could all help! In addition, it's possible that when evaluating **global accuracy**, they only evaluated on the first **11 classes** i.e the non-void ones. So there are some differences there. If you want to fully replicate the paper, it's always best to contact the authors :). But this repo should provide you with an easy to use test bed. :)

Thanks for pointing that out though! Probably good to clarify in the README.
