### ISSUE TITLE
training blocked by reading images

### ISSUE THREAD

**Issue by lixiang-ucas** [GeorgeSeif/Semantic-Segmentation-Suite#32]
Hello, GeorgeSeif, i'm training large amount of data using GPUs, and found the feeding process it too slow, it cost me about 0.5s per image, nearly comparable to the network learning time, i'd recommend you to use a FIFO Queue to avoid the block of feeding data into TF, this would make this repo more excellent.

**Comment by GeorgeSeif** [comment]
Hi there,

Yup I'm actually currently working on getting a TF Records the TensorFlow Dataset API going so that's coming soon!

**Comment by lixiang-ucas** [comment]
Nice work!

**Comment by zengzhi2015** [comment]
Hi, it is found in my test that the reading (plus augmentation) speed of images is too slow. (Approx. 1 second per one) Is there a method to solve this?
