### ISSUE TITLE
how to make label for myself dataset 

### ISSUE THREAD

**Issue by sry984789463** [GeorgeSeif/Semantic-Segmentation-Suite#33]
Hello!I have a question for you. The question is how to make a colored label, in other words, how to make the original black label into a colored label in the data set.Thank you !!

**Comment by fotsing365** [comment]
Hello me too I am facing to this problem now I would like to know if there is app which can help me to label image like Camvid dataset.  I actually use pain but result is not kind

**Comment by GeorgeSeif** [comment]
I've never personally tried any, but Wikipedia lists many popular ones:

https://en.wikipedia.org/wiki/List_of_manual_image_annotation_tools

I've heard good things about both RectLabel and LabelBox!
