### ISSUE TITLE
UNET Model

### ISSUE THREAD

**Issue by Joeng22** [GeorgeSeif/Semantic-Segmentation-Suite#36]
Can you add U-Net model also?

**Comment by Joeng22** [comment]
Advantages of Mobile-Unet over U-net???

**Comment by GeorgeSeif** [comment]
U-Net is very similar to the `Encoder-Decoder with skip connections` model in the repo. Just a few changes to the convolutions parameters which you can alter.

MobileNet has less parameters and is faster

**Comment by Joeng22** [comment]
Ok, Thank you
