### ISSUE TITLE
Bug in DeeplabV3+ implementation

### ISSUE THREAD

**Issue by abiro** [GeorgeSeif/Semantic-Segmentation-Suite#38]
Hi,

I think there is a bug in the DeeplabV3+ implementation. On [lines 110-111](https://github.com/GeorgeSeif/Semantic-Segmentation-Suite/blob/78508277a41da265e745ea377b5c9b694da3c4d1/models/DeepLabV3_plus.py#L110) the `conv2d` functions `encoder_features`, but they should take `net` as argument. Currently this has the effect of ignoring the `AtrousSpatialPyramidPoolingModule` in the output.

What do you think?

**Comment by GeorgeSeif** [comment]
You're absolutely right! I just fixed it.

I also moved the 1x1 conv right after the `AtrousSpatialPyramidPoolingModule` (but before the first upsampling) to outside of the `AtrousSpatialPyramidPoolingModule` for clarity.

Thanks!
