### ISSUE TITLE
--continue_training: Boolean value expected.

### ISSUE THREAD

**Issue by enomto** [GeorgeSeif/Semantic-Segmentation-Suite#44]
--continue_training CONTINUE_TRAINING
                         Whether to continue training from a checkpoint
How do you do on the command?

**Comment by GeorgeSeif** [comment]
Check out this function in the `main.py` code:

```
def str2bool(v):
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')
```

So to train using a previous checkpoint, you can pass any of the following: ('yes', 'true', 't', 'y', '1')

Cheers!
