### ISSUE TITLE
Suggession - add new loss - LovaszSoftmax

### ISSUE THREAD

**Issue by maksimovkonstantin** [GeorgeSeif/Semantic-Segmentation-Suite#45]
Hi!

Thanks for great repo!

I tried to add LovaszSoftmax loss from here - https://github.com/bermanmaxim/LovaszSoftmax - but with no success yet. It shows promising results on direct IoU fit.

Maybe you will be more successful?

**Comment by GeorgeSeif** [comment]
Looks good! I'll give that a go once I have a chance?

Are you currently working on implementation or have you implemented it and just aren't getting the same result yet?

**Comment by maksimovkonstantin** [comment]
@GeorgeSeif I made port from pytroch version, but loss don't go done, some error happend.

**Comment by maksimovkonstantin** [comment]
@GeorgeSeif here is tf implementation - https://github.com/bermanmaxim/LovaszSoftmax

**Comment by GeorgeSeif** [comment]
Oh nice. I'll give it a try soon!

**Comment by GeorgeSeif** [comment]
Okay so I added the loss and modified it a bit to fit into the code. But I'm getting some bad results, as in with this loss, nothing is changing at all. If you like you can try it out by using the `loss_func` command line argument. I'll try and take a crack at it later on.

Cheers!
