### ISSUE TITLE
CamVid example fails with _csv.Error error while openning class_dict.csv file

### ISSUE THREAD

**Issue by sanja7s** [GeorgeSeif/Semantic-Segmentation-Suite#47]
The full error I have got is below:

"Semantic-Segmentation-Suite/helpers.py", line 29, in get_label_info
    header = next(file_reader)
**_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)**

So I have changed the corresponding line in the helpers.py from:

with open(csv_path, 'rb') as csvfile:

to:

**with open(csv_path, 'r') as csvfile:**

to make it work.

Not sure if others would experience the same problem, but maybe helpful if they do.

**Comment by GeorgeSeif** [comment]
You're right! Thanks for reminding me, it was actually in a previous issue but I forget to update it. Will do right now
