### ISSUE TITLE
Checkpoints for the models we run

### ISSUE THREAD

**Issue by sanja7s** [GeorgeSeif/Semantic-Segmentation-Suite#49]
Hi George,

Thanks a lot for the great repo you created. I find it very useful.

One suggestion is to add control for the number of checkpoints that are actually saved when we run our own models.

Namely, I run 300 iterations just to test and ended up running out of hard disk, since there are more than 80GB of checkpoints created. Probably we would be fine with one after every N=10 or 100 saved.
What do you think?

**Comment by GeorgeSeif** [comment]
Good call! 

I just added command line options to set how often checkpoints are saved and how often validation is performed.

Cheers!
