### ISSUE TITLE
Pre-trained Tiramisu model

### ISSUE THREAD

**Issue by alasin** [GeorgeSeif/Semantic-Segmentation-Suite#5]
Hi,

Thanks for open-sourcing your work. I was wondering if you have a pre-trained weights for the Tiramisu network? 

Thanks

**Comment by GeorgeSeif** [comment]
Ah unfortunately I deleted them after I posted the results to the README. :(

But it was very easy to obtain the decent results I posted in README! I just trained using those default settings I have in the `main.py` file (with RMS prop), default crop size, and no data augmentation.
