### ISSUE TITLE
Evaluation including precision, recall, f1 score, average accuracy, per-class accuracy, and mean IoU

### ISSUE THREAD

**Issue by enomto** [GeorgeSeif/Semantic-Segmentation-Suite#50]
I am afraid the result is wrong?

Why does the value of an object not included in the image come out?
Why does the calculation result differ even if specifying the same label with csv?
ex)
background = 0.949837
background = 1.000000

**Comment by GeorgeSeif** [comment]
The result of an object not included comes out simply for cleanliness of code, it's easier to just print all labels every time.. It says 1.000000 when the label is not included in the image. And it should be the same in the CSV and in terminal when printing.
