### ISSUE TITLE
pre-training

### ISSUE THREAD

**Issue by enomto** [GeorgeSeif/Semantic-Segmentation-Suite#51]
Is it possible to learn the data of output 3 as pre-training after learning with output data of 20? (I want to learn my own data after learning VOC)
I do not know how to pre-training.

Thank you for quite useful code.

**Comment by GeorgeSeif** [comment]
It's definitely possible though I doubt you would get a descent accuracy. Because your pre-training classes are less than your new classes, your model just might not generalize well enough.

Give it a try though!
