### ISSUE TITLE
How to use your own pre-training

### ISSUE THREAD

**Issue by enomto** [GeorgeSeif/Semantic-Segmentation-Suite#55]
How can I use "model.ckpt.data-00000-of-00001, model.ckpt.index, model.ckpt.meta" as "pre-training" as my own data?
What kind of arguments can I pass?

Thank you.

**Comment by FirstCaptain** [comment]
along the same lines, after doing the training how do you do a prediction based upon your trained model data?

**Comment by GeorgeSeif** [comment]
Just set the command line argument --continue_training to true @enomto .

And just select the appropriate mode using the command line argument --mode @FirstCaptain

**Comment by FirstCaptain** [comment]
@GeorgeSeif Thanks I understand that I need to use --mode predict, but do I pass in the model that it finished training --model my_model.cpkt or --continue_training True so that it used the model I have trained rather than just the base model.

**Comment by enomto** [comment]
"--continue_training true" does not work if the number of classifications is different.
In the pre-model, the number of classifications can be different by learning only the output layer.
Is "--continue_training true" different from "pre-model"?

**Comment by GeorgeSeif** [comment]
Well of course it doesn't work because the networks are now different! The
"continue_training" is only for specifically continuing the training of the
same model on the same dataset. That's why I named it that way :)

**Comment by enomto** [comment]
That is, you can not do "Pre-model = fine-tuning".
understood. Thank you for your reply.
