### ISSUE TITLE
CamVid database labels

### ISSUE THREAD

**Issue by 1451154** [GeorgeSeif/Semantic-Segmentation-Suite#6]
Thanks for your code！CamVid database's label is color image(RGB)，but your train_labels、val_labels and test_labels are  gray image。Can you tell me why you want to convert these annotated color images into grayscale images and how to convert them?
This is your train_labels:
![0001tp_006690](https://user-images.githubusercontent.com/35360587/35311738-f7348d28-00f2-11e8-8842-94f1e6532218.png)
This is CamVid' label:
![0001tp_006690_l](https://user-images.githubusercontent.com/35360587/35312129-eeef8a26-00f4-11e8-975b-38d7c316911a.png)

**Comment by GeorgeSeif** [comment]
I'm actually using an older version of CamVid where the labels came in grayscale. With this older version, each pixel has an integer value of its class  from 0 to 11 (CamVid had 12 classes at the time).

Though it does seem you found a flaw I shall fix! As the "one_hot_it" function in "helpers.py" won't currently work with those colour labels. I'll try and fix this ASAP!

**Comment by GeorgeSeif** [comment]
Updated! It now works with the colour labels and thus the original CamVid dataset!

**Comment by chenwydj** [comment]
> I'm actually using an edited version of CamVid which is commonly used in research papers. With this different version, each pixel has an integer value of its class from 0 to 11 (CamVid had 12 classes at the time).
> 
> Though it does seem you found a flaw I shall fix! As the "one_hot_it" function in "helpers.py" won't currently work with those colour labels. I'll try and fix this ASAP!

Hi George! I found in the "edited version of CamVid" the image and label has size of (320, 480) which is different from the origin size (720, 960). How did you solve this issue when you were using the "edited version of CamVid" for training and evaluation?

Thank you!
