### ISSUE TITLE
pre-model

### ISSUE THREAD

**Issue by enokazu** [GeorgeSeif/Semantic-Segmentation-Suite#64]
Are there plans to become pre-training rather than continuing learning?

I have large-scale data and want to acquire the weight of each network with that data.
I would like to learn as pre-training of various data using that weight. However, because continuous training can not change data and the number of outputs can not be changed, it will not be realized.

Thank you for the useful code.

**Comment by GeorgeSeif** [comment]
Please see the FAQ in the issue template, and also use the template for future issues.

Thanks!
