### ISSUE TITLE
Test and Validation not clear

### ISSUE THREAD

**Issue by sanja7s** [GeorgeSeif/Semantic-Segmentation-Suite#65]
Dear George,

I apologize if this turns out to be a too simple question, but I am having an issue figuring out what happens with the test images folder. I would expect that when we run the main.py with the mode -- test, it will use those images, but it actually runs prediction on val images.

What does it mean; are the test images ever used? I am looking at the code, and perhaps will figure out soon, but in any case, I think the naming is a bit confusing -- if the mode is called **test** and it uses **val** images and not **test** images.

Thanks a lot!
Sanja

**Comment by GeorgeSeif** [comment]
Yes you are right, that test basically means validation! It will test out the accuracy on the validation set, whereas prediction mode simply runs that network on the image to get the output (without computing any metrics).

Sorry for the confusion! :)

**Comment by sanja7s** [comment]
Thanks for the answer. can you just confirm to me -- the test dataset is
not actually used at any point then (unless I select to predict on images
from it?)

Thanks,
Sanja
