### ISSUE TITLE
DeepLabv3_plus issue with the type of size=feature_map_shape

### ISSUE THREAD

**Issue by sanja7s** [GeorgeSeif/Semantic-Segmentation-Suite#66]
When trying to run DeepLabV3_plus, I had this error:

`Traceback (most recent call last):
  File "main.py", line 180, in <module>
    network, init_fn = build_deeplabv3_plus(net_input, preset_model = args.model, num_classes=num_classes)
  File "models/DeepLabV3_plus.py", line 103, in build_deeplabv3_plus
    decoder_features = Upsampling(net, label_size / 4)
  File "models/DeepLabV3_plus.py", line 10, in Upsampling
    return tf.image.resize_bilinear(inputs, size=feature_map_shape)
...
TypeError: Input 'size' of 'ResizeBilinear' Op has type float64 that does not match expected type of int32.`

and solved it by editing line 10 of the code for the model (DeepLabV3_plus.py) to look as below (cast the type of size):

    `return tf.image.resize_bilinear(inputs, size=tf.cast(feature_map_shape, tf.int32))`

**Comment by GeorgeSeif** [comment]
Thanks for that, just updated the code with that!
