### ISSUE TITLE
 Incompatible shapes: [1,512,512] vs. [2] in binary problem after activating --class_balancing

### ISSUE THREAD

**Issue by smajida** [GeorgeSeif/Semantic-Segmentation-Suite#68]
2. Bug reports
------------------------
## Please specify the following information when submitting an issue:
- **What are your command line arguments?python main.py --num_epochs 50 --mode train --dataset AerialLane18_512 --model DeepLabV3_plus-Res50 --class_balancing True
- **Have you written any custom code?**: No
- **TensorFlow version?**: 1.8.0

### Describe the problem
In a binary problem of segmenting lanes and nonlanes, activating --class_balancing throws the following error:
`***** Begin training *****
Dataset --> AerialLane18_512
Model --> DeepLabV3_plus-Res50
Crop Height --> 512
Crop Width --> 512
Num Epochs --> 50
Batch Size --> 1
Num Classes --> 2
Data Augmentation:
	Vertical Flip --> False
	Horizontal Flip --> False
	Brightness Alteration --> None
	Rotation --> None

Traceback (most recent call last):
  File "main.py", line 317, in <module>
    _,current=sess.run([opt,loss],feed_dict={net_input:input_image_batch,net_output:output_image_batch})
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,512,512] vs. [2]
	 [[Node: mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape_2, mul/y)]]
	 [[Node: Mean_1/_717 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3560_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'mul', defined at:
  File "main.py", line 202, in <module>
    losses = unweighted_loss * class_weights
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 979, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1211, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4759, in mul
    "Mul", x=x, y=y, name=name)
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/azim_se/.virtualenvs/objdetTF2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,512,512] vs. [2]
	 [[Node: mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape_2, mul/y)]]
	 [[Node: Mean_1/_717 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3560_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
`

### Source code / logs

class_dict.csv
name,r,g,b
lane,128,50,100
nonlane,0, 0, 0

**Comment by GeorgeSeif** [comment]
Hi there, thanks very much for filling out the issue template!

Hmm I might be missing multiplying the class weights by the one hot labels and doing reduce sum like so `weights = tf.reduce_sum(class_weights * onehot_labels, axis=1)` after I changed the code a few times. See this link which I what I used to do the class weight balancing: https://stackoverflow.com/questions/44560549/unbalanced-data-and-weighted-cross-entropy

Mind trying something like that out and letting me know?

Sorry, I've been without a GPU for a little bit now but will be bringing new updates soon once I buy a new one :)

**Comment by smajida** [comment]
@GeorgeSeif thanks a lot for your reply. first of all I tried with CamVid dataset which you have provided and I changed nothing and got a similar error.

`InvalidArgumentError (see above for traceback): Incompatible shapes: [1,512,512] vs. [31]
	 [[Node: mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape_2, mul/y)]]
	 [[Node: Mean_1/_721 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3563_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`


Regarding your suggestion:

After examination of the problem and also reading through the Stackoverflow question, it seems as you said the tf.reduce_sum is missing. However, onehot_labels are missing.


I tried a weighted loss of sigmoid for binary segmentation task called  weighted_cross_entropy_with_logits
https://www.tensorflow.org/api_docs/python/tf/nn/weighted_cross_entropy_with_logits
and it seems it is working in this case.

There is also another weighted loss, but not sure what difference it has with your version.
https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/losses/compute_weighted_loss

**Comment by GeorgeSeif** [comment]
Ah yes, when you use the `weighted_cross_entropy_with_logits`, I don't think you'll have a softmax function being applied to the output and so results won't be good at all!

Try using the full line I suggested like so:
```
if args.class_balancing:
    print("Computing class weights for", args.dataset, "...")
    class_weights = utils.compute_class_weights(labels_dir=args.dataset + "/train_labels", label_values=label_values)
    weights = tf.reduce_sum(class_weights * net_output, axis=1)
    unweighted_loss = None
    if args.loss_func == "cross_entropy":
        unweighted_loss = tf.nn.softmax_cross_entropy_with_logits(logits=network, labels=net_output)
    elif args.loss_func == "lovasz":
        unweighted_loss = utils.lovasz_softmax(probas=network, labels=net_output)
    losses = unweighted_loss * class_weights
```

And I put the multi-GPU there because someone suggested it, though I haven't tried it myself! :)

**Comment by GeorgeSeif** [comment]
Also I'll fix the naming of things soon. I think the `network` and `net_output` names can be very confusing :)

**Comment by smajida** [comment]
Oh I did not know net_ouput is onehot_labels. Yeah, the names are a little confusing.

Using your suggestion, I ran the following command with no changes in the code:
`$ python main.py --num_epochs 50 --mode train --class_balancing True --dataset CamVid --batch_size 8 --num_val_images 50 --h_flip True --v_flip True --rotation 359 --model DeepLabV3_plus-Res50 --validation_step 5 --checkpoint_step 5`

and got another error:

`Processing image: 420 / 421classweights are:
Traceback (most recent call last):
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 31 and 32 for 'mul' (op: 'Mul') with input shapes: [31], [?,?,?,32].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 209, in <module>
    weights = tf.reduce_sum(class_weights * net_output, axis=1)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 995, in r_binary_op_wrapper
    return func(x, y, name=name)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1211, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4759, in mul
    "Mul", x=x, y=y, name=name)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 31 and 32 for 'mul' (op: 'Mul') with input shapes: [31], [?,?,?,32].`

**Comment by GeorgeSeif** [comment]
I might have some bad old code in the computing of the class weights. Try commenting out these two lines in the `utils.compute_class_weights()` function:

**Comment by smajida** [comment]
I did not change any thing in the code. I commented out those lines however another error arises(see below).  I investigated the problem. `utils.compute_class_weights()` function is giving correct outputs. The problem comes from `weights = tf.reduce_sum(class_weights * net_output, axis=1)` in which `net_output` is initialized with net_output = `tf.placeholder(tf.float32,shape=[None,None,None,num_classes])` and as a result the shape of `weights` is (batchsize,W,H, num_classes) without commenting out those two lines and `(num_classes)` with commented-out, while the shape of `unweighted_loss` is (batchsize,W,H). 

It seems `net_output` should be replaced with onehot_labels with shape of (batchsize,W,H). I am looking into `helpers.one_hot_it`
        


I commented out those two lines and the following error happened:
`python main.py --num_epochs 50 --mode train --class_balancing True --dataset CamVid --batch_size 8 --num_val_images 50 --h_flip True --v_flip True --rotation 359 --model DeepLabV3_plus-Res50 --validation_step 5 --checkpoint_step 5
`
`***** Begin training *****
Dataset --> CamVid
Model --> DeepLabV3_plus-Res50
Crop Height --> 512
Crop Width --> 512
Num Epochs --> 50
Batch Size --> 8
Num Classes --> 32
Data Augmentation:
	Vertical Flip --> True
	Horizontal Flip --> True
	Brightness Alteration --> None
	Rotation --> 359.0

2018-06-10 03:51:40.937770: W tensorflow/core/framework/allocator.cc:101] Allocation of 268435456 exceeds 10% of system memory.
Traceback (most recent call last):
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [8,512,512] vs. [32]
	 [[Node: mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape_2, mul_1/y)]]
	 [[Node: Mean_1/_721 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3563_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 343, in <module>
    _,current=sess.run([opt,loss],feed_dict={net_input:input_image_batch,net_output:output_image_batch})
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [8,512,512] vs. [32]
	 [[Node: mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape_2, mul_1/y)]]
	 [[Node: Mean_1/_721 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3563_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'mul_1', defined at:
  File "main.py", line 222, in <module>
    losses = unweighted_loss * weights
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 979, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1211, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4759, in mul
    "Mul", x=x, y=y, name=name)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/majid/.virtualenvs/cv-py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [8,512,512] vs. [32]
	 [[Node: mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape_2, mul_1/y)]]
	 [[Node: Mean_1/_721 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3563_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`

`classweights are:[3.31629612e-04 3.33184195e-05 2.61163580e-06 3.69554596e-05
 6.01410570e-08 4.10232932e-07 5.18736517e-05 4.99590854e-05
 1.35053498e-06 9.31123677e-07 7.80790606e-07 1.39711051e-04
 2.12458031e-06 2.83819715e-04 3.14808960e-06 3.86920166e-06
 2.09474226e-06 5.05297317e-08 6.43632312e-06 2.11480315e-07
 1.17687158e-05 8.76572352e-08 2.34447481e-06 4.04545136e-04
 3.62955257e-06 1.29480515e-07 3.15362459e-06 9.98619668e-01
 1.85173122e-06 4.44594728e-07 1.03044204e-06]`

**Comment by GeorgeSeif** [comment]
Oh wow so just a typo it looks like... nice find!

Hmm yes, I'd imagine it should gave the same output shape as `tf.nn.softmax_cross_entropy_with_logits`.

Wait, are you currently using the code you have in your pull request? If so then why do you have a separate If-Else statement for binary vs multi-class segmentation?

**Comment by GeorgeSeif** [comment]
Because of course, in order for the shapes to workout, you'll still need to do the whole `weights = tf.reduce_sum(class_weights * net_output, axis=-1)`, and make sure your `class_dict.csv` is setup correctly.

**Comment by smajida** [comment]
yes I am using the code in the pull request, but with one small change. I set `if num_classes> 2: #multi-class segmentation` to be `if num_classes:# > 2: #multi-class segmentation`.
Yes it is not a clean programming, but I use it in this way until I will figure out why using `tf.nn.weighted_cross_entropy_with_logits` with the same weight for positive class does not give comparable results. 

The reason for that if-else statement is to compare tensorflow's built-in `tf.nn.weighted_cross_entropy_with_logits` loss function for binary segmentation with using your implementation.

`class_dict.csv` is setup correctly. 
That would be good if you could explain to me why `tf.nn.weighted_cross_entropy_with_logits` and your implementation yields results with considerable difference.

I will close this issue as it seems this implementation is correct based on your response.

**Comment by GeorgeSeif** [comment]
Ah, as I mentioned in a previous comment, if you use `tf.nn.weighted_cross_entropy_with_logits()` then you won't have a Softmax function at the end of the network! That will make results drastically worse!

**Comment by smajida** [comment]
That is true. We don't have softmax. However, for binary problem we don't need softmax. `tf.nn.weighted_cross_entropy_with_logits() ` uses `sigmoid` for binary segmentation. Am I missing something?

**Comment by GeorgeSeif** [comment]
Hhmm I'm honestly not sure at the moment. I think they should be the same.
Because to select the correct class, I choose the index with the max score.

What exactly do you mean by "bad results" by the way? As in is the output
worse? Does the loss explode? If the loss is exploding it could just be the
difference in the absolute scalar loss that is computed at the end (between
sigmoid and softmax) and maybe just tweaking some optimizer params will
help.

**Comment by GeorgeSeif** [comment]
Closing since the original issue has been solved
