### ISSUE TITLE
Suggestion: saving models as graph.pb

### ISSUE THREAD

**Issue by robertomoreu** [GeorgeSeif/Semantic-Segmentation-Suite#79]
Hello!
I would really like to try out some of these models and see if they work on an android device. So a nice feature would be adding an option to save the model as a .pb graph, as well as the already saved .ckpt. :)

**Comment by GeorgeSeif** [comment]
Ah yes, thanks for the suggestion Robert!

It's actually already in the README under "Coming Soon" :)

Cheers!

**Comment by gulingfengze** [comment]
Any new developments？

**Comment by robertomoreu** [comment]
Hello @gulingfengze ! I managed to get the .pb graphs, but since I did many personal tweaks to the code I did not commit it to the project. What you can do is use the already saved checkpoint files and convert them. This is only possible if you know the names of the input and output layers of the network, which I believe is only possible doing some changes to the architecture code. Once you have all this you can use the "freeze_graph" provided by tensorflow to get the .pb, and the "optimize_for_inference" to clean it up a bit. 
If you are still interested you can reach out :) @GeorgeSeif If I find some time I could add this to the project if you want. Your repo was really really helpful 👍 🥇
