### ISSUE TITLE
When using class balance

### ISSUE THREAD

**Issue by yejg2017** [GeorgeSeif/Semantic-Segmentation-Suite#80]
When I try class_balance,I got this error.don't know how to solve it

Preparing the model ...
Computing class weights for CamVid ...
Processing image: 420 / 421Traceback (most recent call last):
  File "/home/ye/user/yejg/SW_DATA/Or/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 31 and 32 for 'mul' (op: 'Mul') with input shapes: [31], [?,?,?,32].

During handling of the above exception, another exception occurred:

**Comment by GeorgeSeif** [comment]
Hmm are you using the latest code? I believe this was fixed in a previous issue

**Comment by yejg2017** [comment]
lastest code?Which version?I do not know,counld you give me the address

**Comment by GeorgeSeif** [comment]
As in do a `git pull origin master` to get the latest :)

**Comment by JeremyLuna** [comment]
I'm getting it, too. CamVids dataset, but my own model.

**Comment by JeremyLuna** [comment]
It looks like smajida has a branch that fixed class balancing

**Comment by moazam0** [comment]
Any update on the fix of this issue, please?

**Comment by GeorgeSeif** [comment]
Removed class balancing for now until I figure out how to properly implement it. Even when fixing the shapes, performance wasn't good
