### ISSUE TITLE
How to run or add eval script?'

### ISSUE THREAD

**Issue by revikiran1991** [GeorgeSeif/Semantic-Segmentation-Suite#82]
Hello George, 
I am quite new to tensorflow.
How to run the eval using tensorboard?
Is the script for eval script is provided?
And when I restart the training why it starts from epoch 0 instead of the check point number?

**Comment by GeorgeSeif** [comment]
This repository does not use tensorboard. And yes you can do evaluation using a command line argument!

Also such usage questions will be better asked on StackOverflow, there's more support there :)

**Comment by revikiran1991** [comment]
Thank you for your reply and clarification. Have a nice day :)
