### ISSUE TITLE
-215 Assertion failed

### ISSUE THREAD

**Issue by Take22** [GeorgeSeif/Semantic-Segmentation-Suite#83]
Hi I'm new in this code and this code is really amazing for test,  so I tested it

but I stucked in error

**command line arguments** : python main.py --num_epochs 200 --mode train --dataset CamVid --model FC-DenseNet56 --batch_size 1 --crop_height 256 --crop_width 256

**I didn't modify or write any custom code**

**software version** : tensorflow 1.5.0, cuda 9.0, cudnn 7.1, opencv-python 3.4.2, anaconda environment(python 3.5.5)

**error messages are below** 

python main.py --num_epochs 200 --mode train --dataset CamVid --model FC-DenseNet56 --batch_size 1 --crop_height 256 --crop_width 256
C:\Users\admin\AppData\Local\conda\conda\envs\tensorflow\lib\importlib\_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
2018-08-08 11:20:55.209524: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-08-08 11:20:56.018553: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
pciBusID: 0000:02:00.0
totalMemory: 12.00GiB freeMemory: 9.67GiB
2018-08-08 11:20:56.059993: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN V, pci bus id: 0000:02:00.0, compute capability: 7.0)
Preparing the model ...
WARNING:tensorflow:From main.py:197: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

This model has 1370264 trainable parameters
Loading the data ...

***** Begin training *****
Dataset --> CamVid
Model --> FC-DenseNet56
Crop Height --> 256
Crop Width --> 256
Num Epochs --> 200
Batch Size --> 1
Num Classes --> 32
Data Augmentation:
        Vertical Flip --> False
        Horizontal Flip --> False
        Brightness Alteration --> None
        Rotation --> None

Traceback (most recent call last):
  File "main.py", line 276, in <module>
    input_image = load_image(train_input_names[id])
  File "main.py", line 93, in load_image
    image = cv2.cvtColor(cv2.imread(path,-1), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.2) c:\projects\opencv-python\opencv\modules\imgproc\src\color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<3,4,-1>,struct cv::Set<0,2,5>,2>::CvtHelper'

what can I do for this ??

Thanks for nice project!!

Kim

**Comment by GeorgeSeif** [comment]
Hmm well it looks like it's failing at opencv's imread. How about trying
putting a try except around the read. Could be that one of your images are
corrupt!

**Comment by Take22** [comment]
OMG it's a python language issue. my folder name written by korean, and python couldn't process 'path' so opencv imread function got error.

I changed my path in english.

and imread has gone! 

thx

**Comment by Hitsaa** [comment]
I also had the same issue. Actually I had mistakenly typed wrong name of image file in my code that I was trying to import. But when I typed the right name of file then this issue was solved.

**Comment by Soumyatrivedi3099** [comment]
> Hi I'm new in this code and this code is really amazing for test, so I tested it
> 
> but I stucked in error
> 
> **command line arguments** : python main.py --num_epochs 200 --mode train --dataset CamVid --model FC-DenseNet56 --batch_size 1 --crop_height 256 --crop_width 256
> 
> **I didn't modify or write any custom code**
> 
> **software version** : tensorflow 1.5.0, cuda 9.0, cudnn 7.1, opencv-python 3.4.2, anaconda environment(python 3.5.5)
> 
> **error messages are below**
> 
> python main.py --num_epochs 200 --mode train --dataset CamVid --model FC-DenseNet56 --batch_size 1 --crop_height 256 --crop_width 256
> C:\Users\admin\AppData\Local\conda\conda\envs\tensorflow\lib\importlib_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
> return f(*args, **kwds)
> 2018-08-08 11:20:55.209524: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
> 2018-08-08 11:20:56.018553: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
> name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
> pciBusID: 0000:02:00.0
> totalMemory: 12.00GiB freeMemory: 9.67GiB
> 2018-08-08 11:20:56.059993: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN V, pci bus id: 0000:02:00.0, compute capability: 7.0)
> Preparing the model ...
> WARNING:tensorflow:From main.py:197: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> 
> Future major versions of TensorFlow will allow gradients to flow
> into the labels input on backprop by default.
> 
> See tf.nn.softmax_cross_entropy_with_logits_v2.
> 
> This model has 1370264 trainable parameters
> Loading the data ...
> 
> ***** Begin training *****
> Dataset --> CamVid
> Model --> FC-DenseNet56
> Crop Height --> 256
> Crop Width --> 256
> Num Epochs --> 200
> Batch Size --> 1
> Num Classes --> 32
> Data Augmentation:
> Vertical Flip --> False
> Horizontal Flip --> False
> Brightness Alteration --> None
> Rotation --> None
> 
> Traceback (most recent call last):
> File "main.py", line 276, in 
> input_image = load_image(train_input_names[id])
> File "main.py", line 93, in load_image
> image = cv2.cvtColor(cv2.imread(path,-1), cv2.COLOR_BGR2RGB)
> cv2.error: OpenCV(3.4.2) c:\projects\opencv-python\opencv\modules\imgproc\src\color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<3,4,-1>,struct cv::Set<0,2,5>,2>::CvtHelper'
> 
> what can I do for this ??
> 
> Thanks for nice project!!
> 
> i received same error do tell how to remove it.

**Comment by Soumyatrivedi3099** [comment]
i have struct issue BGR2GAY cvt anybody please help.
