### ISSUE TITLE
Using Gray-scale images as input of semantic segmentation master suit

### ISSUE THREAD

**Issue by aminaria** [GeorgeSeif/Semantic-Segmentation-Suite#87]
Hi there!

I want to see if I can use gray-scale images as the input of main.py. Doing so, I think, the code will run much faster since we will have only one channel instead of three. Am I right? 

If yes, what should I do? Should I just change the following line or I should make some further changes? 
  
 image = cv2.cvtColor(cv2.imread(path,-1), cv2.COLOR_BGR2RGB)

**Comment by GeorgeSeif** [comment]
Closing due to lack of recent activity
