### ISSUE TITLE
Suggestion: data augmentation

### ISSUE THREAD

**Issue by Tamme** [GeorgeSeif/Semantic-Segmentation-Suite#9]
Hi!

Its a great suite of capabilities for training models for segmentation! My suggestion would be to add more data augmentation, because that always makes models better and more generic. For example all the things that Keras has (https://keras.io/preprocessing/image/): rotation, zooming to certain parts of the image etc.

**Comment by GeorgeSeif** [comment]
I'll throw some more in when I have a chance!

**Comment by GeorgeSeif** [comment]
I added a couple more!
