### ISSUE TITLE
What should I do to extract good results?

### ISSUE THREAD

**Issue by zmqp111** [GeorgeSeif/Semantic-Segmentation-Suite#91]
Hi there.

I used our dataset to make predictions after learning.

But, result is not good...

this picture is my result.
![image](https://user-images.githubusercontent.com/13760439/45140576-2f60b580-b1ee-11e8-8ee4-56c3f5adc0c1.png)

as you can see, my results seem to be not upsampling.

my dataset is ...

![image](https://user-images.githubusercontent.com/13760439/45140781-e4936d80-b1ee-11e8-85b6-c0024b023c71.png)

What should I do to extract good results?

**Comment by GeorgeSeif** [comment]
Could you please fill out the issue template such that we have enough information to help your?

Thanks!

**Comment by zmqp111** [comment]
Hi GeorgeSeif,
Thanks to your answer.

I used my dataset for training using your code, validation result is very good, but predict is not good.

It seems as if the up-sampling is not performed.

Can you improve the outcome of predict?

**Comment by GeorgeSeif** [comment]
Closing for now due to lack of information
