### ISSUE TITLE
something wrong when generate an image

### ISSUE THREAD

**Issue by 1453042287** [GeorgeSeif/Semantic-Segmentation-Suite#96]
i did not modify the code ，but when i use the dataset bdd100k to train this model ， in the checkpoints folder ，i got stange pictures like this ：
this is a figure generated at validation stage，
7d2f7975-e0c1c5a7_gt.png
![7d2f7975-e0c1c5a7_gt](https://user-images.githubusercontent.com/41471119/45371925-46543d00-b61e-11e8-9769-62f4bb977514.png)
and it’ss actually should be like this：
![7d2f7975-e0c1c5a7_train_color](https://user-images.githubusercontent.com/41471119/45371951-58ce7680-b61e-11e8-8e7b-0bd9ad14c572.png)
can you give me some suggestions ？thanks a lot ！

**Comment by GeorgeSeif** [comment]
Wow, I've never seen anything like that! Could be some kind of data corruption.

What do your labels look like? @1453042287

**Comment by 1453042287** [comment]
@GeorgeSeif thanks a lot, i found the reason is that the version of opencv is incompatible, i upgrade the opencv from 3.1 to 3.3 and the bug is disappear, by the way, which version of tensorflow should i use?
