### ISSUE TITLE
predict.py example

### ISSUE THREAD

**Issue by SerinaWei** [GeorgeSeif/Semantic-Segmentation-Suite#97]
Can you please provide a command line example for running predict.py?

When i try to run predict.py, I always get the error about invalid checkpoint format. For example:

python predict.py --image Images/0001TP_008550.png --crop_height=320 --crop_width=320 --model=PSPNet --checkpoint_path=models/resnet/resnet_v2_101.ckpt 

I run the util/ get_pretrained_checkpoints.py and saved resnet_v2_101.ckpt in models/resnet

The error I got is:

Tensor name "BatchNorm/beta" not found in checkpoint files models/resnet/resnet_v2_101.ckpt

**Comment by GeorgeSeif** [comment]
Well resnet_v2_101.ckpt isn't a segmentation checkpoint, it's a classification checkpoint! You'll need to train a model first if you want to use predict and then used **that** checkpoint as the one for predict :)

**Comment by SerinaWei** [comment]
Got it. Thanks!
